### ISSUE TITLE
yo - hard to contact you.

### ISSUE THREAD

**Issue by roughpandaz** [sohkai/dcl-dao-upgrades#1]
## Description:
You wrote a great post about the state of NFT-backed loans, and it would be great to chat about something we can work on that may change this.

**I liked** 
- how you guys broke out MetaStreet into its section.
- gave a perspective on this can be applied to real-world assets on the day.

**suggestions:**
- i feel that p2pool are actually _less_ scalable, as they depend on Oracles as it's hard to build oracles for each NFT collection.
- premature liquidations is also another challenge (BendDAO).

## Ideas:
Would love to show y'all what we working on. Our protocol aims to offer the best lender/borrower experience.
We allow:
- Lenders with ALL risk tolerances to participate.
- Lenders to better share risk
- Smaller lenders to participate in bigger loans.
- Borrowers to get the highest LTV at optimal rates.

## Todos:
- [ ] @sohkai want to do a short call?

**Comment by sohkai** [comment]
Closing, connected through Twitter DMs.
